name: Student Code Check

on:
  pull_request:
    types:
      - opened
    branches:
      - reto-001

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Check repository
      run: |
        if [[ "$GITHUB_REPOSITORY" != "Hexcss/grade-checking-automation" ]]; then
          echo "This workflow only runs on the original repository."
          exit 1
        fi

    - name: Check for unauthorized changes
      run: |
        git fetch origin master:master
        CHANGED_FILES=$(git diff --name-only origin/master..HEAD)
        if echo "$CHANGED_FILES" | grep -q "^\.github/workflows/"; then
          echo "Unauthorized changes detected in workflow files!"
          exit 1
        fi

    - name: Set up JDK 20
      uses: actions/setup-java@v2
      with:
        java-version: '20'
        distribution: 'temurin'

    - name: Check project structure
      run: |
        for student_dir in entregas/*; do
          if [ -d "$student_dir" ]; then
            # Check if expected directories/files are present in the student's submission
            if [ ! -d "$student_dir/src/main/org/example/java" ]; then
              echo "$student_dir is missing src/main/org/example/java directory!" >> structure-result.txt
            fi
            if [ ! -d "$student_dir/src/test/java" ]; then
              echo "$student_dir is missing src/test/java directory!" >> structure-result.txt
            fi
          fi
        done

    - name: Run Maven tests for all students
      run: |
        for student_dir in entregas/*; do
          if [ -d "$student_dir" ] && [ -f "$student_dir/pom.xml" ]; then
            echo "Running tests for $student_dir"
            cd "$student_dir"
            mvn mvn -B package --file pom.xml || echo "Tests failed for $student_dir!" >> ../test-result.txt
            cd ../..
          fi
        done


    - name: Comment if structure is incorrect
      uses: actions/github-script@v5
      if: steps.build.outputs.structure-result == 'failure'
      with:
        script: |
          const fs = require('fs');
          const structureResult = fs.readFileSync('structure-result.txt', 'utf8');
          github.issues.createComment({
            issue_number: context.issue.number,
            owner: context.repo.owner,
            repo: context.repo.repo,
            body: structureResult
          });

    - name: Comment if tests failed
      uses: actions/github-script@v5
      if: steps.build.outputs.test-result == 'failure'
      with:
        script: |
          const fs = require('fs');
          const testResult = fs.readFileSync('test-result.txt', 'utf8');
          github.issues.createComment({
            issue_number: context.issue.number,
            owner: context.repo.owner,
            repo: context.repo.repo,
            body: testResult
          });
